version: '1.0'
services:
  frontend:
    image: frontend-image:latest
    build:
      context: https://github.com/mhdusop/GAN-Skin-Disease-Identifier.git#frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  backend:
    image: backend-image:latest
    build:
      context: https://github.com/mhdusop/GAN-Skin-Disease-Identifier.git#backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
